---

- include_vars: "{{ansible_distribution}}.yml"

- name: Adding repository
  apt_repository:
    repo: "{{ backup_duplicity_ppa }}"
    state: present
  when: backup_duplicity_ppa is defined

- name: Install dependencies
  apt: name={{ dependencies }}

- set_fact: backup_duplicity_pkg="{{backup_duplicity_pkg}}={{backup_duplicity_version}}"
  when: backup_duplicity_version

- name: Install duplicity
  apt: pkg={{backup_duplicity_pkg}}
